# This is a basic workflow to help you get started with Actions

# This is a basic workflow to help you get started with Actions

name: Run action

# trigger action on every push 
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  run-action:
    # The type of runner that the job will run on
    runs-on: [ubuntu-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # define job setup checkout
      - name: Checkout 
        uses: actions/checkout@v2

      # define job setup Setup python
      - name: Setup python
        uses: actions/setup-python@v2
        with:
           python-version: "3.x"

      # define job setup Check python version 
      - name: Check python version
        run: python --version
